### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [dwisiswant0/slackcat#2]
Great tool ❤❤

Can you introduce a silent flag that doesn't spit out output but just posts to slack.

**Comment by dwisiswant0** [comment]
Hi @nine9-nine9, thanks for the feedback & suggestion!
Looks like the workaround you're talking about could easily use `&>/dev/null` to suppress _stdin_ messages.

**Comment by ghost** [comment]
How about adding which channel to send output to??
